#ifndef MDI_ICONS_40_H
#define MDI_ICONS_40_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

    /* Declare the font generated by LVGL’s font converter */
    LV_FONT_DECLARE(mdi_icons_40);

/* Optional convenience defines for your 7 icons.
 * Replace the \UXXXXXXXX sequences with the actual codepoints
 * shown by the font converter for your chosen icons. Use 8-digit
 * escapes for codepoints above 0xFFFF.
 */
/* Fill these with the exact codepoints from your subset export */
#define MDI_THERMOMETER "\U000F050F" /* thermometer */
#define MDI_GAUGE "\U000F029A"       /* gauge */
#define MDI_CLOCK "\U000F051B"       /* clock-outline */
#define MDI_COG "\U000F0493"         /* cog */
#define MDI_POWER "\U000F0425"       /* power */
#define MDI_STEAM "\U000F1799"       /* weather-fog or smoke, pick what you added */
#define MDI_BEAKER "\U000F0CEA"
#define MDI_COFFEE "\U000F109F"

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* MDI_ICONS_40_H */
