#ifndef MDI_ICONS_40_H
#define MDI_ICONS_40_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

    /* Declare the font generated by LVGL’s font converter */
    LV_FONT_DECLARE(mdi_icons_40);

/* Optional convenience defines for your 7 icons.
 * Replace the \uXXXX with the actual codepoints
 * shown by the font converter for your chosen icons.
 */
/* Fill these with the exact codepoints from your subset export */
#define MDI_THERMOMETER "\uF050F" /* thermometer */
#define MDI_GAUGE "\uF029A"       /* gauge */
#define MDI_CLOCK "\uF051B"       /* clock-outline */
#define MDI_COG "\uF0493"         /* cog */
#define MDI_POWER "\uF0425"       /* power */
#define MDI_STEAM "\uF1799"       /* weather-fog or smoke, pick what you added */
#define MDI_BEAKER "\uF068F"

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* MDI_ICONS_40_H */
