#ifndef MDI_ICONS_24_H
#define MDI_ICONS_24_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

    /* Declare the font generated by LVGL’s font converter */
    LV_FONT_DECLARE(mdi_icons_24);

/* Optional convenience defines for your 7 icons.
 * Replace the \UXXXXXXXX sequences with the actual codepoints
 * shown by the font converter for your chosen icons. Use 8-digit
 * escapes for codepoints above 0xFFFF.
 */
/* Fill these with the exact codepoints from your subset export */
#define MDI_THERMOMETER "\U000F050F" /* thermometer */
#define MDI_GAUGE "\U000F029A"       /* gauge */
#define MDI_CLOCK "\U000F051B"       /* clock-outline */
#define MDI_COG "\U000F0493"         /* cog */
#define MDI_POWER "\U000F0425"       /* power */
#define MDI_STEAM "\U000F1799"       /* weather-fog or smoke, pick what you added */
#define MDI_BEAKER "\U000F0690"
#define MDI_MQTT_ON "\U000F12CC"
#define MDI_MQTT_OFF "\U000F0164"
#define MDI_WIFI_ON "\U000F05A9"
#define MDI_WIFI_OFF "\U000F05AA"
#define MDI_ESP_NOW_ON "\U000F1538"
#define MDI_ESP_NOW_PAIR "\U000F0003"
#define MDI_ESP_NOW_OFF "\U000F1511"
#define MDI_RESET "\U000F04E6"
#define MDI_COFFEE "\U000F181B"

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* MDI_ICONS_24_H */
