#ifndef MDI_ICONS_80_H
#define MDI_ICONS_80_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

    /* Declare the font generated by LVGL’s font converter */
    LV_FONT_DECLARE(mdi_icons_80);

#include "icon_defs.h"

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* MDI_ICONS_80_H */
