name: Bump version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump:
    if: "!contains(github.event.head_commit.message, 'chore: release')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine next version
        id: bump
        run: |
          latest=$(git describe --tags --abbrev=0 || echo v0.0.0)
          latest=${latest#v}
          IFS='.' read -r major minor patch <<< "$latest"
          repo=${GITHUB_REPOSITORY#*/}
          if [[ "$repo" == *-dev ]]; then
            minor=$((minor + 1))
            patch=0
          else
            patch=$((patch + 1))
          fi
          echo "version=v$major.$minor.$patch" >> $GITHUB_OUTPUT
      - name: Update version and tag release
        run: |
          full_version=${{ steps.bump.outputs.version }}
          version=${full_version#v}
          sed -i "s/#define VERSION \".*\"/#define VERSION \"${version}\"/" firmware/shared/include/version.h
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: release ${version}" || echo 'No changes'
          git tag -a "$full_version" -m "$full_version"
          git push origin HEAD --tags
