name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump:
    if: "!contains(github.event.head_commit.message, 'chore: release')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update version in firmware
        run: |
          version=${{ steps.tag.outputs.new_tag }}
          version=${version#v}
          sed -i "s/#define VERSION \".*\"/#define VERSION \"${version}\"/" firmware/shared/include/version.h
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: release ${version}" || echo 'No changes'
          git push
